require("config.lazy")
require("config.lsp")
require("config.mappings")
require("config.config")
require("config.colors")

require("plugins.neotree")
require("plugins.treesitter")
require("plugins.cmp")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.hop")
require("plugins.gitsigns")
