require("config.lazy")
require("config.mappings")
require("config.config")
require("config.colors")

require("plugins.treesitter")
require("plugins.neotree")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.gitsigns")
