require("config.packer")
require("config.lsp")
require("config.mappings")
require("config.config")
require("config.colors")

require("plugins.treesitter")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.neotree")
require("plugins.cmp")
require("plugins.mason")
